openresty:
  image: ibenchu/openresty
  ports:
    - "80:80"
    - "443:443"
  volumes:
  #   # app
  - /home/wwwroot:/home/wwwroot
  #   # nginx configs
  - ./config/conf:/usr/local/openresty/nginx/conf
  - /home/log/nginx/conf:/home/log/nginx
  links:
  - php:php
 


php:
  image: ibenchu/php
  ports:
    - "9000:9000"
    - "9501:9501"

  links:
     - redis:redis
     - pgsql:postgres
  volumes:
    # NOTE: your data will be stored in ./mysql
    - ./config/php.ini:/usr/local/etc/php/php.ini
    - ./config/php-fpm.conf:/usr/local/etc/php/php-fpm.conf
    - /home/wwwroot:/home/wwwroot
  

pgsql:
  image: postgres:alpine
  ports:
    - "5432:5432"
  volumes:
       - /home/data/pgsql:/var/lib/postgresql/data
  environment:
       - POSTGRES_PASSWORD=ibenchu123
       
mariadb:
  image: mariadb:latest
  ports:
    # Allow client to access 3306
    - "3306:3306"
  volumes:
    # NOTE: your data will be stored in ./mysql
    - /home/data/mariadb:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=ibenchu123
  command: ['mysqld', '--character-set-server=utf8']

redis:
  image: redis:alpine
  command: redis-server --requirepass redis
  container_name: redis
  ports: 
    - "6379:6379"
  