#docker 搭建lnmp开发环境

#php   7.1.10
#mysql 5.7.20
#nginx 1.13.5

#Authors: 545922113@qq.com
#Date: 2017-10-24

version: '2'
services:
    #构建nginx
    nginx:
        #指定dockerf所在路径　
        build:
            context: ./nginx
            dockerfile: dockerfile
        #暴露端口(主机:容器)
        ports:
            - "81:80"
            - "443:443"
        #数据卷所挂载的路径　(host:container),有访问模式 (host:container:ro)
        volumes:
            #- ./web/:/var/www/html/:rw                      #网站源码
            - ./web/:/usr/share/nginx/html/:rw               #默认
            - ./nginx/conf.d:/etc/nginx/conf.d/:ro          #配置文件目录　　
            #- ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro   #nginx主配置
            - ./nginx/logs/:/var/log/nginx/:rw            #nginx日记文件
        #设置环境变量
        environment:
            - RACK_ENV=development
        #指定容器名称
        container_name: nginx
        #链接到其他服务中的容器,同时作为别名,(服务器名称:服务器别名)
        links:
            - php
        #指定容器重启的策略
        restart: always


    #php部分
    php:
        build:
            context: ./php
            dockerfile: dockerfile
        ports:
            - "9000:9000"
        volumes:
            - ./web/:/var/www/html/:rw
            - ./php/php.ini:/usr/local/etc/php/php.ini:ro
            #- ./php/php-fpm.d/www.conf/:/usr/local/etc/php-fpm.d/www.conf:rw
            - ./php/logs/php-fpm/:/var/log/php-fpm/:rw
        container_name: php
        links:
            - mysql
        restart: always


    #mysql部分
    mysql:
        build:
            context: ./mysql
            dockerfile: dockerfile
        ports:
            - "3305:3306"
        volumes:
            - ./mysql/mysql.cnf:/etc/mysql/conf.d/:ro
            - ./mysql/data:/var/lib/mysql/:rw
            - ./mysql/logs/:/var/log/mysql/:rw
        #此处是为了解决mysql的编码问题,防止中文乱码
        command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --init-connect='SET NAMES utf8;' --innodb-flush-log-at-trx-commit=0
        environment:
            #设置mysql root用户初始密码为123456
            - MYSQL_ROOT_PASSWORD=123456
        container_name: mysql
        restart: always




